# Generated by Django 5.2.3 on 2025-07-20 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('prompt_template', models.TextField()),
                ('preview_image_url', models.URLField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='styles', to='products.genre')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paddle_plan_id', models.CharField(max_length=6, unique=True)),
                ('generations_count', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('total_price_usage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unlocked_styles', models.ManyToManyField(to='products.style')),
            ],
        ),
    ]
