# Generated by Django 5.2.3 on 2026-01-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('stars_count', models.IntegerField()),
                ('generations_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Star Package',
                'verbose_name_plural': 'Star Packages',
            },
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
