# Generated by Django 5.2.3 on 2025-07-30 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='preview_image_url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
