# Generated by Django 5.2.3 on 2025-08-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_style_preview_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='preview_image_url',
        ),
    ]
