# Generated by Django 5.2.3 on 2026-02-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_starpackage_delete_subscriptionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starpackage',
            name='stars_count',
        ),
        migrations.AddField(
            model_name='starpackage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='starpackage',
            name='stars_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
