# Generated by Django 5.2.3 on 2026-02-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_starpackage_stars_count_starpackage_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='starpackage',
            name='stars_counts',
        ),
        migrations.AddField(
            model_name='starpackage',
            name='countries_t1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='starpackage',
            name='stars_count_t1',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='starpackage',
            name='stars_count_t2',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
