# Generated by Django 5.2.3 on 2025-08-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_style_preview_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8),
        ),
    ]
