# Generated by Django 5.2.3 on 2026-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_starpackage_stars_counts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
