# Generated by Django 5.2.3 on 2025-08-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_subscriptionplan_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='total_price_usage',
            new_name='product_price',
        ),
    ]
