# Generated by Django 5.2.3 on 2025-12-01 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('privacy_policy', 'Privacy Policy'), ('cookie_policy', 'Cookie Policy'), ('refund_policy', 'Refund Policy'), ('dmca_policy', 'DMCA Policy')], max_length=40)),
                ('version', models.DecimalField(decimal_places=2, max_digits=10)),
                ('content', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Terms Version',
                'verbose_name_plural': 'Terms Versions',
                'indexes': [models.Index(fields=['-published_at'], name='agreements__publish_1cf1ef_idx')],
                'unique_together': {('document_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('context', models.JSONField(default=dict)),
                ('terms_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_agreements', to='agreements.termsversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Agreement',
                'verbose_name_plural': 'User Agreements',
                'indexes': [models.Index(fields=['-accepted_at'], name='agreements__accepte_150223_idx'), models.Index(fields=['ip_address'], name='agreements__ip_addr_77b27b_idx')],
                'unique_together': {('user', 'terms_version')},
            },
        ),
    ]
