# Generated by Django 5.2.3 on 2025-09-27 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='termsversion',
            index=models.Index(fields=['-published_at'], name='agreements__publish_1cf1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='useragreement',
            index=models.Index(fields=['-accepted_at'], name='agreements__accepte_150223_idx'),
        ),
        migrations.AddIndex(
            model_name='useragreement',
            index=models.Index(fields=['ip_address'], name='agreements__ip_addr_77b27b_idx'),
        ),
    ]
