# Generated by Django 5.2.3 on 2025-11-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0002_termsversion_agreements__publish_1cf1ef_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsversion',
            name='document_type',
            field=models.CharField(choices=[('terms_of_service', 'Terms of Service'), ('privacy_policy', 'Privacy Policy'), ('cookie_policy', 'Cookie Policy'), ('refund_policy', 'Refund Policy'), ('dmca_policy', 'DMCA Policy')], max_length=40),
        ),
    ]
