# Generated by Django 5.2.3 on 2025-09-14 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=20)),
                ('cancels_at', models.DateTimeField(blank=True, null=True)),
                ('paddle_subscription_id', models.CharField(max_length=255, unique=True)),
                ('remaining_credits', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='products.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'indexes': [models.Index(fields=['user', 'status'], name='user_status_idx'), models.Index(condition=models.Q(('remaining_credits__gt', 0), ('status', 'active')), fields=['user', 'end_time'], name='user_active_credits_end_idx')],
            },
        ),
    ]
