# Generated by Django 5.2.3 on 2025-12-14 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(db_index=True)),
                ('is_auto_renew', models.BooleanField(default=True)),
                ('rec_token', models.CharField(blank=True, max_length=255, null=True)),
                ('order_reference', models.CharField(max_length=255, unique=True)),
                ('remaining_credits', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='products.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'indexes': [models.Index(fields=['user', 'end_time', 'remaining_credits'], name='user_end_time_credits_idx'), models.Index(fields=['user', 'is_auto_renew'], name='user_auto_renew_idx')],
            },
        ),
    ]
