# Generated by Django 5.2.3 on 2025-07-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
