# Generated by Django 5.2.3 on 2025-08-15 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_subscriptionplan_price'),
        ('subscriptions', '0002_usersubscription_cancels_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(condition=models.Q(('remaining_credits__gt', 0), ('status', 'active')), fields=['user', 'end_time'], name='user_active_credits_end_idx'),
        ),
    ]
