# Generated by Django 5.2.3 on 2025-12-01 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_thumb_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('input_large_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('output_thumb_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('output_large_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('output_original_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('rejected_by_safety', 'Rejected By Safety'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chosen_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_requests', to='products.style')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generation Request',
                'verbose_name_plural': 'Generation Requests',
                'indexes': [models.Index(fields=['user', 'is_visible', 'is_hidden', '-created_at'], name='user_visible_hidden_idx'), models.Index(fields=['user', 'is_hidden', '-created_at'], name='user_hidden_created_idx'), models.Index(fields=['user', '-created_at'], name='user_latest_req_idx'), models.Index(fields=['-created_at'], name='gen_req_created_at_desc_idx')],
            },
        ),
    ]
