# Generated by Django 5.2.3 on 2025-09-14 14:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_img_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('output_img_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_api_message', models.TextField(blank=True, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chosen_style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generation_requests', to='products.style')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Generation Request',
                'verbose_name_plural': 'Generation Requests',
                'indexes': [models.Index(fields=['user', 'status', 'is_hidden', '-created_at'], name='u_s_ih_ca_idx')],
            },
        ),
    ]
