# Generated by Django 5.2.3 on 2026-02-20 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0001_initial'),
        ('products', '0005_style_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generationrequest',
            name='user_visible_hidden_idx',
        ),
        migrations.RemoveIndex(
            model_name='generationrequest',
            name='user_hidden_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='generationrequest',
            name='gen_req_created_at_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='generationrequest',
            new_name='user_created_at_idx',
            old_name='user_latest_req_idx',
        ),
        migrations.RemoveField(
            model_name='generationrequest',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='generationrequest',
            name='is_hidden',
        ),
        migrations.RemoveField(
            model_name='generationrequest',
            name='is_visible',
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='status',
            field=models.CharField(choices=[('rejected_by_safety', 'Rejected By Safety'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['user', 'status', '-created_at'], name='user_status_created_at_idx'),
        ),
    ]
