# Generated by Django 5.2.3 on 2025-08-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
    ]
