# Generated by Django 5.2.3 on 2025-09-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped_by_user', 'Stopped By User'), ('rejected_by_safety', 'Rejected By Safety')], db_index=True, default='processing', max_length=20),
        ),
    ]
