# Generated by Django 5.2.3 on 2026-02-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0002_remove_generationrequest_user_visible_hidden_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='type',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('paid', 'Paid')], max_length=20, null=True),
        ),
    ]
