# Generated by Django 5.2.3 on 2025-08-15 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0002_alter_generationrequest_status'),
        ('products', '0004_alter_subscriptionplan_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generationrequest',
            options={'verbose_name': 'Generation Request', 'verbose_name_plural': 'Generation Requests'},
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['user', 'status', '-created_at'], name='user_status_created_at_idx'),
        ),
    ]
