# Generated by Django 5.2.3 on 2025-08-20 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0003_alter_generationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrequest',
            name='input_img_url',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
