# Generated by Django 5.2.3 on 2026-02-25 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0003_generationrequest_type'),
        ('products', '0005_style_is_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['status', 'type'], name='status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['-created_at'], name='created_at_idx'),
        ),
    ]
