# Generated by Django 5.2.3 on 2025-09-27 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0003_alter_generationrequest_user'),
        ('products', '0002_alter_subscriptionplan_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generationrequest',
            name='u_s_ih_ca_idx',
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['user', 'is_hidden', '-created_at'], name='user_hidden_created_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['user', '-created_at'], name='user_latest_req_idx'),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['-created_at'], name='gen_req_created_at_desc_idx'),
        ),
    ]
