# Generated by Django 5.2.3 on 2025-10-19 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0004_remove_generationrequest_u_s_ih_ca_idx_and_more'),
        ('products', '0002_alter_subscriptionplan_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generationrequest',
            name='user_hidden_created_idx',
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='input_img_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='output_img_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='status',
            field=models.CharField(choices=[('rejected_by_safety', 'Rejected By Safety'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['user', 'is_visible', '-created_at'], name='user_visible_created_idx'),
        ),
    ]
