# Generated by Django 5.2.3 on 2025-08-21 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0004_alter_generationrequest_input_img_url'),
        ('products', '0004_alter_subscriptionplan_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generationrequest',
            name='user_status_created_at_idx',
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['user', 'status', 'is_hidden', '-created_at'], name='u_s_ih_ca_idx'),
        ),
    ]
