# Generated by Django 5.2.3 on 2025-10-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0005_remove_generationrequest_user_hidden_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationrequest',
            name='input_large_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='input_thumb_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='output_large_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='output_original_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='generationrequest',
            name='output_thumb_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='input_img_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='generationrequest',
            name='output_img_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
