# Generated by Django 5.2.3 on 2025-10-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0006_generationrequest_input_large_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationrequest',
            name='error_api_message',
        ),
    ]
