# Generated by Django 5.2.3 on 2025-10-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0007_remove_generationrequest_error_api_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generationrequest',
            name='input_img_url',
        ),
        migrations.RemoveField(
            model_name='generationrequest',
            name='output_img_url',
        ),
    ]
