# Generated by Django 5.2.3 on 2025-10-26 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0008_remove_generationrequest_input_img_url_and_more'),
        ('products', '0002_alter_subscriptionplan_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='generationrequest',
            name='user_visible_created_idx',
        ),
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['user', 'is_visible', 'is_hidden', '-created_at'], name='user_visible_hidden_idx'),
        ),
    ]
