# Generated by Django 5.2.3 on 2025-10-27 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0009_remove_generationrequest_user_visible_created_idx_and_more'),
        ('products', '0002_alter_subscriptionplan_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='generationrequest',
            index=models.Index(fields=['user', 'is_hidden', '-created_at'], name='user_hidden_created_idx'),
        ),
    ]
