# Generated by Django 5.2.3 on 2025-11-24 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generations', '0010_generationrequest_user_hidden_created_idx'),
        ('products', '0002_alter_subscriptionplan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationrequest',
            name='chosen_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_requests', to='products.style'),
        ),
    ]
