# Generated by Django 5.2.3 on 2026-02-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpurchase',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
