# Generated by Django 5.2.3 on 2025-12-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_credits',
            field=models.IntegerField(default=3),
        ),
    ]
