# Generated by Django 5.2.3 on 2025-07-15 13:30

import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted_terms_version',
            field=models.CharField(default=users.models.get_current_terms_version),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
