# Generated by Django 5.2.3 on 2025-12-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_free_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='free_credits',
            field=models.IntegerField(default=5),
        ),
    ]
