# Generated by Django 5.2.3 on 2025-07-20 11:54

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_accepted_terms_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accepted_terms_version',
            field=models.CharField(default=users.models.get_current_terms_version, max_length=6),
        ),
    ]
