# Generated by Django 5.2.3 on 2026-01-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='free_credits',
            new_name='credits',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.IntegerField(default=2),
        ),
    ]
