# Generated by Django 5.2.3 on 2026-02-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_free_credits_userprofile_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.IntegerField(default=1),
        ),
    ]
