# Generated by Django 5.2.3 on 2026-02-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
