# Generated by Django 5.2.3 on 2026-02-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invited_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
