# Generated by Django 5.2.3 on 2026-02-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile_invited_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='credits',
            new_name='free_credits',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paid_credits',
            field=models.IntegerField(default=0),
        ),
    ]
