# Generated by Django 5.2.3 on 2025-08-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registration_enabled', models.BooleanField(default=True)),
                ('hard_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reserved_for_spend', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Application Configuration',
            },
        ),
    ]
