# Generated by Django 5.2.3 on 2026-01-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationconfig',
            name='hard_budget',
        ),
        migrations.RemoveField(
            model_name='applicationconfig',
            name='is_registration_enabled',
        ),
        migrations.AddField(
            model_name='applicationconfig',
            name='generations_reserved',
            field=models.IntegerField(default=0),
        ),
    ]
