# Generated by Django 5.2.3 on 2026-02-01 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_applicationconfig_hard_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationconfig',
            old_name='generations_reserved',
            new_name='reserved_generations',
        ),
    ]
