# Generated by Django 5.2.3 on 2025-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_applicationconfig_hard_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationconfig',
            name='hard_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
