# Generated by Django 5.2.3 on 2026-02-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_generations_reserved_applicationconfig_reserved_generations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_free_generations_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Application Analytics',
            },
        ),
        migrations.DeleteModel(
            name='ApplicationConfig',
        ),
    ]
