# Generated by Django 5.2.3 on 2026-02-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applicationanalytics_delete_applicationconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationAnalytics',
            new_name='Application',
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application'},
        ),
    ]
